[package]
name = "rustpython-derive"
version = "0.1.2"
description = "Rust language extensions and macros specific to rustpython."
authors = ["RustPython Team"]
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.91", features = ["full", "extra-traits"] }
syn-ext = { version = "0.3.1", features = ["full"] }
quote = "1.0.18"
proc-macro2 = "1.0.37"
rustpython-compiler = { path = "../compiler/porcelain", version = "0.1.1" }
rustpython-bytecode = { path = "../bytecode", version = "0.1.1" }
maplit = "1.0.2"
once_cell = "1.10.0"
textwrap = { version = "0.15.0", default-features = false }
indexmap = "1.8.1"
itertools = "0.10.3"
